name: Deploy

on:
  push:
    branches:
      - development
      - production

env:
  ENVIRONMENT: ${{ github.ref_name }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Hey
        run: |
          echo "Current Branch is ${{ env.ENVIRONMENT }}"
