name: Deploy

on:
  push:
    branches:
      - development
      - production

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Hey
        run: |
          echo "Current Branch is ${{ github.ref_name }}"
